// This file is automatically generated. Do not modify it.
// See the @firebase/backend quickstart guide for more information: https://firebase.google.com/docs/build
import { initializeApp, getApp, getApps } from 'firebase/app';

const firebaseConfig = {"apiKey":"API_KEY","authDomain":"PROJECT_ID.firebaseapp.com","projectId":"PROJECT_ID","storageBucket":"PROJECT_ID.appspot.com","messagingSenderId":"SENDER_ID","appId":"APP_ID"};

function getFirebaseApp() {
  if (getApps().length) {
    return getApp();
  }
  return initializeApp(firebaseConfig);
}

export { getFirebaseApp };
